name: Continuous Delivery

on: [push]

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.4.0
      with:
        name: meuArtefato.zip
        path: |
          '**.py'
          README.md

  deploy:
    runs-on: ubuntu-latest
    needs: deliver
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.8
      with:
        name: meuArtefato.zip
    - name: Display structure of downloaded files
      run: ls -R